version: '3.9'
services:
  redis:
    image: redis/redis-stack:latest
    restart: always
    container_name: redis-search
    mem_limit: 512m
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: redis-stack-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data/redis-data
volumes:
  redis-data: