version: '3.9'
services:
  search-service:
    container_name: search-service
    restart: always
    image: springboot/search-service
    build: ./
    mem_limit: 512M
    ports:
      - '8080:8080'
  search-frontend:
    container_name: search-frontend
    image: react/search-frontend
    build: ./front-end/autosuggest-search-bar
    ports:
      - '5173:5173'
    depends_on:
      - search-service 
      - redis
    restart: always
    mem_limit: 512M
  redis:
    image: redis/redis-stack:latest
    restart: always
    container_name: redis-search
    mem_limit: 512m
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: redis-stack-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data/redis-data
volumes:
  redis-data: